=== 0wlyW00d/misp-objects/schema_objects.json
{
  "$schema": "http://json-schema.org/schema#",
  "additionalProperties": false,
  "defs": {
    "attribute": {
      "additionalProperties": false,
      "properties": {
        "categories": {
          "items": {
            "type": "string"
          },
          "type": "array",
          "uniqueItems": true
        },
        "description": {
          "type": "string"
        },
        "disable_correlation": {
          "type": "boolean"
        },
        "misp-attribute": {
          "type": "string"
        },
        "multiple": {
          "type": "boolean"
        },
        "recommended": {
          "type": "boolean"
        },
        "sane_default": {
          "items": {
            "type": "string"
          },
          "type": "array",
          "uniqueItems": true
        },
        "to_ids": {
          "type": "boolean"
        },
        "ui-priority": {
          "type": "number"
        },
        "values_list": {
          "items": {
            "type": "string"
          },
          "type": "array",
          "uniqueItems": true
        }
      },
      "required": [
        "misp-attribute",
        "ui-priority",
        "description"
      ],
      "type": "object"
    }
  },
  "id": "https://www.github.com/MISP/misp-objects/schema.json",
  "properties": {
    "attributes": {
      "additionalProperties": {
        "$ref": "#/defs/attribute",
        "type": "object"
      },
      "type": "object"
    },
    "description": {
      "type": "string"
    },
    "meta-category": {
      "enum": [
        "file",
        "network",
        "financial",
        "misc",
        "internal",
        "vulnerability",
        "climate"
      ],
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "required": {
      "items": {
        "type": "string"
      },
      "type": "array",
      "uniqueItems": true
    },
    "requiredOneOf": {
      "items": {
        "type": "string"
      },
      "type": "array",
      "uniqueItems": true
    },
    "uuid": {
      "type": "string"
    },
    "version": {
      "type": "integer"
    }
  },
  "required": [
    "attributes",
    "version",
    "description",
    "meta-category",
    "name",
    "uuid"
  ],
  "title": "Validator for misp-objects",
  "type": "object"
}

=== 0wlyW00d/misp-objects/objects/movie/definition.json
{
  "attributes": {
    "duration": {
      "description": "Duration of the movie.",
      "disable_correlation": true,
      "misp-attribute": "counter",
      "ui-priority": 1
    },
    "plot": {
      "description": "Plot of the movie.",
      "disable_correlation": true,
      "misp-attribute": "text",
      "ui-priority": 1
    },
    "release-date": {
      "description": "Date when the movie was released.",
      "disable_correlation": true,
      "misp-attribute": "datetime",
      "ui-priority": 1
    },
    "title": {
      "description": "Title of the movie.",
      "disable_correlation": true,
      "misp-attribute": "text",
      "ui-priority": 1
    }
  },
  "description": "A movie object describing a movie.",
  "meta-category": "misc",
  "name": "movie",
  "required": [
    "title"
  ],
  "uuid": "da01ac0d-b9cd-4942-9974-c7ab9a199fbd",
  "version": 1
}

=== 0wlyW00d/misp-objects/objects/btc-wallet/definition.json
{
  "requiredOneOf": [
    "wallet-address"
  ],
  "attributes": {
    "wallet-address": {
      "description": "A Bitcoin wallet address",
      "ui-priority": 0,
      "misp-attribute": "btc"
    },
    "balance_BTC": {
      "description": "Value in BTC at date/time displayed in field 'time'",
      "ui-priority": 0,
      "disable_correlation": true,
      "misp-attribute": "float"
    },
    "balance_EUR": {
      "description": "Value in EUR with conversion rate as of date/time displayed in field 'time'",
      "ui-priority": 0,
      "disable_correlation": true,
      "misp-attribute": "float"
    },
    "balance_USD": {
      "description": "Value in USD with conversion rate as of date/time displayed in field 'time'",
      "ui-priority": 0,
      "disable_correlation": true,
      "misp-attribute": "float"
    },
    "time": {
      "description": "Date and time of lookup/conversion",
      "ui-priority": 0,
      "disable_correlation": true,
      "misp-attribute": "datetime"
    }
  },
  "version": 1,
  "description": "An object to describe a Bitcoin wallet. Best to be used with bitcoin-transactions.",
  "meta-category": "financial",
  "uuid": "22910C83-DD0E-4ED2-9823-45F8CAD562A4",
  "name": "btc-wallet"
}

=== 0wlyW00d/misp-objects/objects/pgp-meta/definition.json
{
  "required": [
    "key"
  ],
  "attributes": {
    "first-seen": {
      "description": "First time the tuple has been seen",
      "disable_correlation": true,
      "ui-priority": 0,
      "misp-attribute": "datetime"
    },
    "last-seen": {
      "description": "Last time the tuple has been seen",
      "disable_correlation": true,
      "ui-priority": 0,
      "misp-attribute": "datetime"
    },
    "key-id": {
      "description": "key-id",
      "ui-priority": 1,
      "misp-attribute": "text",
      "multiple": true
    },
    "user-id-email": {
      "description": "User ID packet, email address of the key holder",
      "ui-priority": 1,
      "misp-attribute": "email-subject",
      "multiple": true
    },
    "user-id-name": {
      "description": "User ID packet, name of the key holder",
      "ui-priority": 1,
      "misp-attribute": "text",
      "multiple": true
    }
  },
  "version": 1,
  "description": "Metadata extracted from a PGP keyblock, message or signature",
  "meta-category": "misc",
  "uuid": "4c9134c4-b3e8-4d9f-b3c0-c683e70ec1dd",
  "name": "pgp-meta"
}

=== 0wlyW00d/misp-objects/objects/command/definition.json
{
  "attributes": {
    "command-name": {
      "description": "Text used to call the command",
      "ui-priority": 1,
      "misp-attribute": "text"
    },
    "functionality": {
      "description": "Functionality of the command",
      "ui-priority": 1,
      "misp-attribute": "text"
    }
  },
  "version": 1,
  "description": "Command",
  "meta-category": "misc",
  "uuid": "21ad70d8-d397-11e9-9ea7-43b2d5f6a6e3",
  "name": "command"
}

=== 0wlyW00d/misp-objects/objects/ilr-notification-incident/definition.json
{
  "attributes": {
    "Nom entreprise": {
      "description": "Nom de l’entreprise notifiee",
      "disable_correlation": true,
      "ui-priority": 0,
      "misp-attribute": "text"
    },
    "date-incident": {
      "description": "Date/heure de la detection de l’incident:",
      "disable_correlation": true,
      "ui-priority": 0,
      "misp-attribute": "datetime"
    },
    "date-pre-notification": {
      "description": "Date de la pre-notification",
      "disable_correlation": true,
      "ui-priority": 0,
      "misp-attribute": "text"
    },
    "impact-servicesw-urgence": {
      "description": "Services d’urgences impactés ?",
      "disable_correlation": true,
      "ui-priority": 0,
      "misp-attribute": "text",
      "values_list": [
        "Oui",
        "Non"
      ]
    },
    "description-probleme-services-urgence": {
      "description": "Description du problème sur les services d’urgences impactes",
      "disable_correlation": true,
      "ui-priority": 0,
      "misp-attribute": "text"
    },
    "delimitation-geographique": {
      "description": "Delimitation geographique",
      "disable_correlation": true,
      "ui-priority": 0,
      "misp-attribute": "text",
      "values_list": [
        "Nationale",
        "Regionale"
      ]
    },
    "zone-impactee": {
      "description": "zones/communes/villes impactees ",
      "disable_correlation": true,
      "ui-priority": 0,
      "multiple": true,
      "misp-attribute": "text"
    },
    "details-service": {
      "description": "Details relatifs au service concerne et à l’impact de l’incident",
      "disable_correlation": true,
      "ui-priority": 0,
      "misp-attribute": "text"
    },
    "cause-initiale-incident": {
      "description": "Cause initiale de l'incident",
      "disable_correlation": true,
      "ui-priority": 0,
      "misp-attribute": "text",
      "values_list": [
        "rreur humaine",
        "Défaut système 'hardware', 'software', 'procédures'",
        "Attaque malveillante",
        "Défaut d’une partie tierce ou externe",
        "Catastrophe naturelle"
      ]
    },
    "autres-informations": {
      "description": "Autres informations concernant la nature de l’incident notamment la liste des actifs affectés et les causes subséquentes éventuelles, déclenchées par la cause initiale ",
      "disable_correlation": true,
      "ui-priority": 0,
      "misp-attribute": "text"
    },
    "description-incident": {
      "description": "Description générale de l’incident",
      "disable_correlation": true,
      "ui-priority": 0,
      "misp-attribute": "text"
    },
    "traitement-incident": {
      "description": "Traitement de l’incident et actions effectuées en ordre chronologique",
      "disable_correlation": true,
      "ui-priority": 0,
      "misp-attribute": "text"
    },
    "actions-posterieur": {
      "description": "Actions posterieures de l’incident pour minimiser le risque ",
      "disable_correlation": true,
      "ui-priority": 0,
      "misp-attribute": "text"
    },
    "interconnections-affectees": {
      "description": "Interconnections nationales et/ou internationales affectees",
      "disable_correlation": true,
      "ui-priority": 0,
      "misp-attribute": "text"
    },
    "actions-corrective": {
      "description": "Actions correctives à long terme",
      "disable_correlation": true,
      "ui-priority": 0,
      "misp-attribute": "text"
    },
    "remarques": {
      "description": "Remarque(s), notamment les experiences gagnees et les leçons tirees de l’incident",
      "disable_correlation": true,
      "ui-priority": 0,
      "misp-attribute": "text"
    },
    "nom-contact-incident": {
      "description": "Nom de la personne de contact en rapport avec l’incident",
      "disable_correlation": true,
      "ui-priority": 0,
      "misp-attribute": "text"
    },
    "telephone-contact-incident": {
      "description": "Telephone de la personne de contact en rapport avec l’incident",
      "disable_correlation": true,
      "ui-priority": 0,
      "misp-attribute": "text"
    },
    "email-contact-incident": {
      "description": "Email de la personne de contact en rapport avec l’incident",
      "disable_correlation": true,
      "ui-priority": 0,
      "misp-attribute": "text"
    }
  },
  "version": 1,
  "description": "Institut Luxembourgeois de Régulation - Notification d'incident",
  "meta-category": "misc",
  "uuid": "b8ade604-39b2-11e9-b753-1fd28d3b612c",
  "name": "ilr-notification-incident"
}

=== 0wlyW00d/misp-objects/objects/pcap-metadata/definition.json
{
  "requiredOneOf": [
    "text",
    "first-packet-seen",
    "last-packet-seen"
  ],
  "attributes": {
    "capture-length": {
      "description": "Capture length set on the captured interface.",
      "disable_correlation": true,
      "ui-priority": 1,
      "misp-attribute": "text"
    },
    "capture-interface": {
      "description": "Interface name where the packet capture was running.",
      "disable_correlation": true,
      "ui-priority": 1,
      "misp-attribute": "text"
    },
    "protocol": {
      "description": "Capture protocol (linktype name).",
      "disable_correlation": true,
      "ui-priority": 1,
      "misp-attribute": "text",
      "sane_default": [
        "LINKTYPE_NULL",
        "LINKTYPE_ETHERNET"
      ]
    },
    "text": {
      "description": "A description of the packet capture.",
      "disable_correlation": true,
      "ui-priority": 1,
      "misp-attribute": "text"
    },
    "first-packet-seen": {
      "description": "When the first packet has been seen.",
      "disable_correlation": true,
      "ui-priority": 0,
      "misp-attribute": "datetime"
    },
    "last-packet-seen": {
      "description": "When the last packet has been seen.",
      "disable_correlation": true,
      "ui-priority": 0,
      "misp-attribute": "datetime"
    }
  },
  "version": 1,
  "description": "Network packet capture metadata",
  "meta-category": "network",
  "uuid": "0784aefa-ec3a-4eca-a431-c31ed7058bd3",
  "name": "pcap-metadata"
}

=== 0wlyW00d/misp-objects/objects/social-media-group/definition.json
{
  "requiredOneOf": [
    "group-name",
    "group-alias",
    "archive",
    "description"
  ],
  "attributes": {
    "group-name": {
      "description": "The name of the group, channel or community.",
      "ui-priority": 1,
      "misp-attribute": "text"
    },
    "description": {
      "description": "A description of the group, channel or community.",
      "ui-priority": 1,
      "misp-attribute": "text"
    },
    "group-alias": {
      "description": "Aliases of group, channel or community.",
      "ui-priority": 1,
      "multiple": true,
      "misp-attribute": "text"
    },
    "platform": {
      "description": "The social media platform used.",
      "ui-priority": 1,
      "misp-attribute": "text",
      "disable_correlation": true,
      "multiple": true,
      "sane_default": [
        "Facebook",
        "Twitter"
      ]
    },
    "username": {
      "description": "A user account who is a member of the group.",
      "ui-priority": 1,
      "misp-attribute": "text",
      "multiple": true
    },
    "administrator": {
      "description": "A user account who is an owner or admin of the group.",
      "ui-priority": 1,
      "misp-attribute": "text",
      "multiple": true
    },
    "person-name": {
      "description": "A person who is a member of the group.",
      "ui-priority": 1,
      "misp-attribute": "text",
      "multiple": true
    },
    "hashtag": {
      "description": "Hashtag used to identify or promote the group.",
      "ui-priority": 0,
      "misp-attribute": "text",
      "multiple": true
    },
    "url": {
      "description": "Original URL location of the group (potentially malicious).",
      "ui-priority": 1,
      "misp-attribute": "url"
    },
    "link": {
      "description": "Original link into the group (supposed harmless).",
      "ui-priority": 1,
      "misp-attribute": "link"
    },
    "embedded-link": {
      "description": "Link embedded in the group description (potentially malicious).",
      "ui-priority": 0,
      "misp-attribute": "url",
      "multiple": true
    },
    "embedded-safe-link": {
      "description": "Link embedded in the group description (supposed safe).",
      "ui-priority": 0,
      "misp-attribute": "link",
      "multiple": true,
      "to_ids": false
    },
    "archive": {
      "description": "Archive of the original group (Internet Archive, Archive.is, etc).",
      "ui-priority": 1,
      "multiple": true,
      "disable_correlation": true,
      "misp-attribute": "link"
    },
    "attachment": {
      "description": "A screen capture or exported list of contacts, group members, etc.",
      "ui-priority": 1,
      "multiple": true,
      "misp-attribute": "attachment"
    }
  },
  "version": 1,
  "description": "Social media group object template describing a public or private group or channel.",
  "meta-category": "misc",
  "uuid": "c4939ec4-ab53-4c35-9a98-3d4d4caf5b6c",
  "name": "social-media-group"
}

=== 0wlyW00d/misp-objects/objects/github-user/definition.json
{
  "attributes": {
    "bio": {
      "description": "Biography of the GitHub user.",
      "misp-attribute": "text",
      "ui-priority": 1
    },
    "profile-image": {
      "description": "Profile image of the GitHub user (it can be multiple).",
      "misp-attribute": "attachment",
      "ui-priority": 1,
      "multiple": true
    },
    "following": {
      "description": "Followed GitHub users by the GitHub user.",
      "misp-attribute": "github-username",
      "ui-priority": 80,
      "multiple": true
    },
    "follower": {
      "description": "GitHub user is followed by.",
      "misp-attribute": "github-username",
      "ui-priority": 79,
      "multiple": true
    },
    "ssh-public-key": {
      "description": "SSH public key associated to the GitHub user.",
      "misp-attribute": "text",
      "ui-priority": 10,
      "multiple": true
    },
    "organisation": {
      "description": "Organisation affiliation of the GitHub user (it can be multiple).",
      "misp-attribute": "github-organisation",
      "multiple": true,
      "ui-priority": 1
    },
    "username": {
      "description": "GitHub username.",
      "misp-attribute": "github-username",
      "multiple": true,
      "ui-priority": 98
    },
    "repository": {
      "description": "GitHub repository under the GitHub user.",
      "misp-attribute": "github-repository",
      "multiple": true,
      "ui-priority": 96
    },
    "user-fullname": {
      "description": "Fullname of the GitHub user.",
      "misp-attribute": "text",
      "ui-priority": 97
    },
    "link": {
      "description": "Original Link to the GitHub account.",
      "misp-attribute": "link",
      "multiple": true,
      "ui-priority": 1
    },
    "verified": {
      "description": "User verified.",
      "disable_correlation": true,
      "misp-attribute": "text",
      "sane_default": [
        "True",
        "False"
      ],
      "ui-priority": 1
    }
  },
  "description": "GitHub user",
  "meta-category": "misc",
  "name": "github-user",
  "requiredOneOf": [
    "username",
    "link"
  ],
  "uuid": "4329b5e6-8e6a-4b55-8fd1-9033782017d4",
  "version": 1
}
