=== 0wlyW00d/misp-objects/schema_objects.json
{
  "$schema": "http://json-schema.org/schema#",
  "additionalProperties": false,
  "defs": {
    "attribute": {
      "additionalProperties": false,
      "properties": {
        "categories": {
          "items": {
            "type": "string"
          },
          "type": "array",
          "uniqueItems": true
        },
        "description": {
          "type": "string"
        },
        "disable_correlation": {
          "type": "boolean"
        },
        "misp-attribute": {
          "type": "string"
        },
        "multiple": {
          "type": "boolean"
        },
        "recommended": {
          "type": "boolean"
        },
        "sane_default": {
          "items": {
            "type": "string"
          },
          "type": "array",
          "uniqueItems": true
        },
        "to_ids": {
          "type": "boolean"
        },
        "ui-priority": {
          "type": "number"
        },
        "values_list": {
          "items": {
            "type": "string"
          },
          "type": "array",
          "uniqueItems": true
        }
      },
      "required": [
        "misp-attribute",
        "ui-priority",
        "description"
      ],
      "type": "object"
    }
  },
  "id": "https://www.github.com/MISP/misp-objects/schema.json",
  "properties": {
    "attributes": {
      "additionalProperties": {
        "$ref": "#/defs/attribute",
        "type": "object"
      },
      "type": "object"
    },
    "description": {
      "type": "string"
    },
    "meta-category": {
      "enum": [
        "file",
        "network",
        "financial",
        "misc",
        "internal",
        "vulnerability",
        "climate"
      ],
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "required": {
      "items": {
        "type": "string"
      },
      "type": "array",
      "uniqueItems": true
    },
    "requiredOneOf": {
      "items": {
        "type": "string"
      },
      "type": "array",
      "uniqueItems": true
    },
    "uuid": {
      "type": "string"
    },
    "version": {
      "type": "integer"
    }
  },
  "required": [
    "attributes",
    "version",
    "description",
    "meta-category",
    "name",
    "uuid"
  ],
  "title": "Validator for misp-objects",
  "type": "object"
}

=== 0wlyW00d/misp-objects/objects/forensic-evidence/definition.json
{
  "required": [
    "case-number",
	  "evidence-number"
  ],
  "attributes": {
	"case-number": {
		"description": "A unique number assigned to the case for unique identification.",
		"ui-priority": 0,
		"misp-attribute": "text"
    },
    "evidence-number": {
      "description": "A unique number assigned to the evidence for unique identification.",
      "ui-priority": 0,
      "misp-attribute": "text"
    },
	"type": {
      "description": "Evidence type.",
      "multiple": true,
      "ui-priority": 0,
      "misp-attribute": "text",
	    "sane_default": [
        "Computer",
        "Network",
        "Mobile Device",
        "Multimedia",
        "Cloud",
        "IoT",
        "Other"
      ],
      "disable_correlation": true
    },
	"name": {
	    "description": "Name",
      "ui-priority": 0,
      "misp-attribute": "text"
	},
	"acquisition-hash-type": {
		  "description": "Hashing algorithm used on the evidence",
		  "multiple": true,
		  "ui-priority": 0,
		  "misp-attribute": "text",
		  "sane_default": [
        "MD5",
        "SHA-1",
        "Other"
      ],
      "disable_correlation": true
	},
	"acquisition-hash": {
	    "description": "Acquisition hash of the evidence",
      "ui-priority": 0,
      "misp-attribute": "text"
	},
  "references": {
      "description": "External references",
      "multiple": true,
      "ui-priority": 0,
      "misp-attribute": "link"
    },
  "additional-comments": {
      "description": "Comments.",
      "ui-priority": 0,
      "misp-attribute": "text"
  },
	"file-upload": {
	    "description": "Upload any file pertaining to the evidence.",
      "ui-priority": 0,
      "misp-attribute": "attachment",
      "multiple": true
	  }
  },
  "version": 1,
  "description": "An object template to describe a digital forensic evidence.",
  "meta-category": "misc",
  "uuid": "fe44c648-63ef-43fc-b3de-af71a2e023e4",
  "name": "forensic-evidence"
}

=== 0wlyW00d/misp-objects/objects/tor-node/definition.json
{
  "requiredOneOf": [
    "address",
    "first-seen",
    "last-seen",
    "text"
  ],
  "required": [
    "address"
  ],
  "attributes": {
    "text": {
      "description": "Tor node description.",
      "disable_correlation": true,
      "ui-priority": 1,
      "misp-attribute": "text"
    },
    "address": {
      "description": "IP address of the Tor node seen.",
      "ui-priority": 1,
      "misp-attribute": "ip-src"
    },
    "last-seen": {
      "description": "When the Tor node designed by the IP address has been seen for the last time.",
      "disable_correlation": true,
      "ui-priority": 0,
      "misp-attribute": "datetime"
    },
    "first-seen": {
      "description": "When the Tor node designed by the IP address has been seen for the first time.",
      "disable_correlation": true,
      "ui-priority": 0,
      "misp-attribute": "datetime"
    }
  },
  "version": 1,
  "description": "Tor node (which protects your privacy on the internet by hiding the connection between users Internet address and the services used by the users) description which are part of the Tor network at a time.",
  "meta-category": "misc",
  "uuid": "a5fde1c8-318e-4658-a3ea-85ea000bdd33",
  "name": "tor-node"
}

=== 0wlyW00d/misp-objects/objects/digital-forensics-case-metadata/definition.json
{
    "requiredOneOf": [
      "case-number",
      "name-of-the-analyst",
      "crime-date",
      "analysis-start-date"
    ],
    "attributes": {
      "case-number": {
        "description": "Any unique number assigned to the case for unique identification.",
        "ui-priority": 0,
        "misp-attribute": "text"
      },
      "case-name": {
        "description": "Name to address the case.",
        "ui-priority": 0,
        "misp-attribute": "text"
      },
      "name-of-the-analyst": {
        "description": "Name(s) of the analyst assigned to the case.",
        "multiple": true,
        "ui-priority": 0,
        "misp-attribute": "text"
      },
      "location-of-the-crime": {
        "description": "Location where the crime took place.",
        "ui-priority": 0,
        "misp-attribute": "text"
      },
      "crime-date": {
        "description": "Date and time when the crime occurred.",
        "ui-priority": 0,
        "misp-attribute": "datetime"
      },
      "describe-the-crime-scene": {
        "description": "Description of the crime scene",
        "ui-priority": 0,
        "misp-attribute": "text"
      },
      "objects-acquired": {
        "description": "Digital evidence acquired from the crime scene.",
        "ui-priority": 0,
        "misp-attribute": "text"
      },
      "references": {
        "description": "External references",
        "multiple": true,
        "ui-priority": 0,
        "misp-attribute": "link"
      },
      "analysis-start-date": {
        "description": "Date when the analysis began.",
        "ui-priority": 0,
        "misp-attribute": "datetime"
      },
      "additional-comments": {
        "description": "Comments.",
        "ui-priority": 0,
        "misp-attribute": "text"
      }
    },
    "version": 1,
    "description": "Describes details of the case under analysis.",
    "meta-category": "misc",
    "uuid": "3ea36022-ae93-455e-88b1-d43aca789cac",
    "name": "Digital forensic - Case info"
  }

=== 0wlyW00d/misp-objects/objects/ss7-attack/definition.json
{
  "attributes": {
    "Category": {
      "description": "Category",
      "disable_correlation": true,
      "misp-attribute": "text",
      "multiple": true,
      "sane_default": [
        "Cat0",
        "Cat1",
        "Cat2.1",
        "Cat2.2",
        "Cat3.1",
        "Cat3.2",
        "Cat3.3",
        "CatSMS",
        "CatSpoofing"
      ],
      "ui-priority": 1
    },
    "GtAssignee": {
      "description": "GT Assignee this is the party that got the GT range assigned by their Regulator.",
      "misp-attribute": "text",
      "multiple": true,
      "ui-priority": 0
    },
    "GtLessee": {
      "description": "GT Lessee is a third party who will use a leased global title from a GT Lessor.",
      "misp-attribute": "text",
      "multiple": true,
      "ui-priority": 0
    },
    "GtLessor": {
      "description": "GT Lessor is a GT Assignee that has decided to lease one or more of their GTs to a third party, the GT Lessee, typically on a commercial basis.",
      "misp-attribute": "text",
      "multiple": true,
      "ui-priority": 0
    },
    "GtSubLessee": {
      "description": "GT Sub-Lessee â€“ this is an additional third party who has entered into an agreement with the GT Lessee to sub-lease a GT from them.",
      "misp-attribute": "text",
      "multiple": true,
      "ui-priority": 0
    },
    "MapApplicationContext": {
      "description": "MAP application context in OID format.",
      "disable_correlation": true,
      "misp-attribute": "text",
       "sane_default": [
        "4.0.0.1.0.1. - networkLocUp ",
        "4.0.0.1.0.2. - locationCancel ",
        "4.0.0.1.0.3. - roamingNbEnquiry ",
        "4.0.0.1.0.22. - subscriberDataModificationNotification ",
        "4.0.0.1.0.6. - callControlTransfer ",
        "4.0.0.1.0.16. - subscriberDataMngt ",
        "4.0.0.1.0.32. - gprsLocationUpdate ",
        "4.0.0.1.0.46. - vcsgLocationUpdate ",
        "4.0.0.1.0.1. - networkLocUp_v1 ",
        "4.0.0.1.0.14. - infoRetrieval_v1 ",
        "4.0.0.1.0.15. - interVlrInfoRetrieval_v1 ",
        "4.0.0.1.0.18. - networkFunctionalSs ",
        "4.0.0.1.0.39. - authenticationFailureReport_v3 ",
        "4.0.0.1.0.18. - networkFunctionalSs_v1 ",
        "4.0.0.1.0.44. - resourceMngt ",
        "4.0.0.1.0.41. - shortMsgMT_VGCS_Relay ",
        "4.0.0.1.0.5. - locInfoRetrieval ",
        "4.0.0.1.0.32. - gprsLocationUpdate_v3 ",
        "4.0.0.1.0.33. - gprsLocationInfoRetrieval_v3_v4 ",
        "4.0.0.1.0.34. - failureReport_v3 ",
        "4.0.0.1.0.35. - gprsNotify ",
        "4.0.0.1.0.11. - handoverControl_v1 ",
        "4.0.0.1.0.11. - handoverControl ",
        "4.0.0.1.0.12. - sIWFSAllocation ",
        "4.0.0.1.0.47. - vcsgLocationCancel ",
        "4.0.0.1.0.10. - reset ",
        "4.0.0.1.0.31. - groupCallControl ",
        "4.0.0.1.0.13. - equipmentMngt ",
        "4.0.0.1.0.25. - shortMsgMT_Relay ",
        "4.0.0.1.0.20. - shortMsgGateway ",
        "4.0.0.1.0.21. - shortMsgMO_Relay ",
        "4.0.0.1.0.24. - mwdMngt_v1 ",
        "4.0.0.1.0.23. - shortMsgAlert_v1 ",
        "4.0.0.1.0.17. - tracing ",
        "4.0.0.1.0.18. - networkFunctionalSs_V1 ",
        "4.0.0.1.0.15. - interVlrInfoRetrievalV2_V3 ",
        "4.0.0.1.0.14. - infoRetrieval_v2_v3 ",
        "4.0.0.1.0.1. - networkLocUp_v2 ",
        "4.0.0.1.0.26. - imsiRetrieval_v2 ",
        "4.0.0.1.0.19. - networkUnstructuredSsv2 ",
        "4.0.0.1.0.19. - networkUnstructuredSs ",
        "4.0.0.1.0.43. - anyTimeInfoHandling ",
        "4.0.0.1.0.23. - shortMsgAlert_v2 ",
        "4.0.0.1.0.24. - mwdMngt_v2_v3 ",
        "4.0.0.1.0.4. - istAlerting_v2_v3 ",
        "4.0.0.1.0.27. - msPurging_v3 ",
        "4.0.0.1.0.11. - handoverControl_v2_v3 ",
        "4.0.0.1.0.28. - subscriberInfoEnquiry ",
        "4.0.0.1.0.29. - anyTimeEnquiryv3 ",
        "4.0.0.1.0.36. - ss_InvocationNotification ",
        "4.0.0.1.0.7. - reporting ",
        "4.0.0.1.0.8. - callCompletion ",
        "4.0.0.1.0.38. - locationSvcEnquiryv3 ",
        "4.0.0.1.0.45. - groupCallInfoRetrieval ",
        "4.0.0.1.0.37. - locationSvcGateway_v3 ",
        "4.0.0.1.0.38. - locationSvcEnquiry ",
        "4.0.0.1.0.4. - istAlerting_v3 ",
        "4.0.0.1.0.9. - ServiceTermination ",
        "4.0.0.1.0.42. - mm_EventReporting "
      ],
      "ui-priority": 0
    },
    "MapGmlc": {
      "description": "MAP GMLC. Phone number.",
      "misp-attribute": "text",
      "ui-priority": 0
    },
    "MapGsmscfGT": {
      "description": "MAP GSMSCF GT. Phone number.",
      "misp-attribute": "text",
      "ui-priority": 0
    },
    "MapImsi": {
      "description": "MAP IMSI. Phone number starting with MCC/MNC.",
      "misp-attribute": "text",
      "multiple": true,
      "ui-priority": 0
    },
    "MapMscGT": {
      "description": "MAP MSC GT. Phone number.",
      "misp-attribute": "text",
      "ui-priority": 0
    },
    "MapMsisdn": {
      "description": "MAP MSISDN. Phone number.",
      "misp-attribute": "text",
      "multiple": true,
      "ui-priority": 0
    },
    "MapOpCode": {
      "description": "MAP operation codes - Decimal value between 0-99.",
      "disable_correlation": true,
      "misp-attribute": "text",
      "ui-priority": 0
    },
    "MapSmsTP-DCS": {
      "description": "MAP SMS TP-DCS.",
      "disable_correlation": true,
      "misp-attribute": "text",
      "ui-priority": 0
    },
    "MapSmsTP-OA": {
      "description": "MAP SMS TP-OA. Phone number.",
      "misp-attribute": "text",
      "ui-priority": 0
    },
    "MapSmsTP-PID": {
      "description": "MAP SMS TP-PID.",
      "disable_correlation": true,
      "misp-attribute": "text",
      "ui-priority": 0
    },
    "MapSmsText": {
      "description": "MAP SMS Text. Important indicators in SMS text.",
      "misp-attribute": "text",
      "ui-priority": 0
    },
    "MapSmsTypeNumber": {
      "description": "MAP SMS TypeNumber.",
      "disable_correlation": true,
      "misp-attribute": "text",
      "ui-priority": 0
    },
    "MapSmscGT": {
      "description": "MAP SMSC. Phone number.",
      "misp-attribute": "text",
      "multiple": true,
      "ui-priority": 0
    },
    "MapUssdCoding": {
      "description": "MAP USSD Content.",
      "disable_correlation": true,
      "misp-attribute": "text",
      "ui-priority": 0
    },
    "MapUssdContent": {
      "description": "MAP USSD Content.",
      "misp-attribute": "text",
      "ui-priority": 0
    },
    "MapVersion": {
      "description": "Map version.",
      "disable_correlation": true,
      "misp-attribute": "text",
      "sane_default": [
        "1",
        "2",
        "3"
      ],
      "ui-priority": 0
    },
    "MapVlrGT": {
      "description": "MAP VLR GT. Phone number.",
      "misp-attribute": "text",
      "ui-priority": 0
    },
    "SccpCdGT": {
      "description": "Signaling Connection Control Part (SCCP) CdGT - Phone number.",
      "misp-attribute": "text",
      "ui-priority": 0
    },
    "SccpCdPC": {
      "description": "Signaling Connection Control Part (SCCP) CdPC - Phone number.",
      "misp-attribute": "text",
      "ui-priority": 0
    },
    "SccpCdSSN": {
      "description": "Signaling Connection Control Part (SCCP) - Decimal value between 0-255.",
      "disable_correlation": true,
      "misp-attribute": "text",
      "ui-priority": 0
    },
    "SccpCgGT": {
      "description": "Signaling Connection Control Part (SCCP) CgGT - Phone number.",
      "misp-attribute": "text",
      "multiple": true,
      "ui-priority": 0
    },
    "SccpCgPC": {
      "description": "Signaling Connection Control Part (SCCP) CgPC - Phone number.",
      "misp-attribute": "text",
      "multiple": true,
      "ui-priority": 0
    },
    "SccpCgSSN": {
      "description": "Signaling Connection Control Part (SCCP) - Decimal value between 0-255.",
      "disable_correlation": true,
      "misp-attribute": "text",
      "ui-priority": 0
    },
    "first-seen": {
      "description": "When the attack has been seen for the first time.",
      "disable_correlation": true,
      "misp-attribute": "datetime",
      "ui-priority": 0
    },
    "text": {
      "description": "A description of the attack seen via SS7 logging.",
      "disable_correlation": true,
      "misp-attribute": "text",
      "multiple": true,
      "ui-priority": 0
    }
  },
  "description": "SS7 object of an attack seen on a GSM, UMTS or LTE network via SS7 logging.",
  "meta-category": "network",
  "name": "ss7-attack",
  "requiredOneOf": [
    "text"
  ],
  "uuid": "f3493d8b-a7ab-48d0-a775-046c4d64d782",
  "version": 3
}

=== 0wlyW00d/misp-objects/objects/fail2ban/definition.json
{
  "required":[
    "banned-ip",
    "processing-timestamp",
    "attack-type"
  ],
  "attributes": {
    "banned-ip": {
      "description": "IP Address banned by fail2ban",
      "ui-priority": 1,
      "misp-attribute": "ipsrc"
    },
    "timestamp": {
      "description": "Timestamp of the report",
      "ui-priority": 1,
      "misp-attribute": "datetime"
    },
    "attack-type": {
      "description": "Type of the attack",
      "ui-priority": 1,
      "misp-attribute": "text"
    },
    "failures": {
      "description": "Amount of failures that lead to the ban.",
      "ui-priority": 1,
      "misp-attribute": "counter"
    },
    "sensor": {
      "description": "Identifier of the sensor",
      "ui-priority": 1,
      "misp-attribute": "text"
    },
    "victim": {
      "description": "Identifier of the victim",
      "ui-priority": 1,
      "misp-attribute": "text"
    }
  },
  "version": 1,
  "description": "Fail2ban event",
  "meta-category": "network",
  "uuid": "8be2271-7326-41a5-a0dd-9b4bec88e1ba",
  "name": "fail2ban"
}

=== 0wlyW00d/misp-objects/objects/regripper-software-hive-appInit-DLLS/definition.json
{
    "required": [
      "key",
      "DLL-name",
      "DLL-path"
    ],
    "attributes": {
      "key": {
        "description": "Software hive key where the information is retrieved from.",
        "ui-priority": 0,
        "misp-attribute": "text"
      },
      "last-write-time": {
        "description": "Date and time when the key was last updated.",
        "ui-priority": 0,
        "misp-attribute": "datetime"
      },
      "DLL-name": {
        "description": "Name of the DLL file.",
        "ui-priority": 0,
        "misp-attribute": "text"
      },
      "DLL-path": {
        "description": "Path where the DLL file is stored.",
        "ui-priority": 0,
        "misp-attribute": "text"
      },
      "DLL-last-write-time": {
        "description": "Date and time when the DLL file was last updated.",
        "ui-priority": 0,
        "misp-attribute": "datetime"
      },
      "comments": {
        "description": "Additional comments.",
        "ui-priority": 0,
        "misp-attribute": "text"
      },
      "references": {
        "description": "References to the DLL file.",
        "ui-priority": 0,
        "misp-attribute": "links",
        "multiple":true
      }
    },
    "version": 1,
    "description": "Regripper Object template designed to gather information of the DLL files installed on the system.",
    "meta-category": "misc",
    "uuid": "7893be05-8398-451e-ab1e-5e25ea4a8859",
    "name": "regripper-software-hive-appInit-DLLS"
  }

=== 0wlyW00d/misp-objects/objects/boleto/definition.json
{
  "name": "boleto",
  "uuid": "24979ac7-d413-4345-9c8b-69b43a739fd1",
  "meta-category": "financial",
  "description": "A common form of payment used in Brazil.",
  "version": 1,
  "attributes": {
    "boleto-number": {
      "categories": [
        "Financial fraud"
      ],
      "misp-attribute": "text",
      "ui-priority": 1,
      "description": "Boleto code numbers"
    },
    "generator-financial-institution": {
      "misp-attribute": "text",
	  "disable_correlation": true,
	  "ui-priority": 1,
      "description": "Name of the bank or financial organisation that created the boleto."
    },
    "febraban-code": {
      "misp-attribute": "text",
	  "disable_correlation": true,
	  "ui-priority": 0,
      "description": "Financial institution code in Brazil that created the boleto."
    },
	"requester": {
	  "misp-attribute": "text",
	  "ui-priority": 1,
      "description": "Organisation, service or affiliated person that requested creation of the boleto."
    },
    "payment-value": {
      "to_ids": false,
      "categories": [
        "Other"
      ],
      "ui-priority": 1,
      "disable_correlation": true,
      "misp-attribute": "float",
      "description": "The payment boleto value in Brazilian Reais"
    },
	"creation-date": {
      "disable_correlation": true,
      "misp-attribute": "datetime",
      "ui-priority": 0,
      "description": "Date the boleto was created"
    },
    "payment-due-date": {
      "disable_correlation": true,
      "misp-attribute": "datetime",
      "ui-priority": 1,
      "description": "Boleto payment date"
    },
    "payment-status": {
      "disable_correlation": true,
	  "ui-priority": 0,
      "misp-attribute": "text",
      "values_list": [
        "Not Paid",
        "Paid"
      ],
      "description": "Inform if boleto was as paid or not"
    },	
    "beneficiary-bank-account": {
	  "categories": [
        "Financial fraud"
      ],
      "misp-attribute": "bank-account-nr",
      "ui-priority": 0,
      "description": "Recipient bank account number"
    },	
    "beneficiary-bank-agency": {
	  "categories": [
        "Financial fraud"
      ],
      "misp-attribute": "bank-account-nr",
      "ui-priority": 0,
      "description": "Recipient bank agency number"
    },
    "beneficiary": {
      "description": "Final beneficiary of the boleto.",
      "misp-attribute": "text",
      "ui-priority": 1
    }
  },
  "requiredOneOf": [
    "boleto-number"
  ]
}

=== 0wlyW00d/misp-objects/objects/cloth/definition.json
{
  "attributes": {
    "description": {
      "description": "Cloth's Description of a natural person",
      "misp-attribute": "text",
      "ui-priority": 50
    },
    "head-accessories": {
      "description": "Cloth and accessories on the head",
      "misp-attribute": "text",
      "multiple": true,
      "ui-priority": 10,
      "values_list": [
        "hat",
        "cap",
        "bonnet",
        "glasses",
        "bandeau"
      ]
    },
    "top-accessories": {
      "description": "Cloth and accessories on the top part of the body",
      "misp-attribute": "text",
      "multiple": true,
      "ui-priority": 10,
      "values_list": [
        "jacket",
        "coat",
        "dress",
        "shirt",
        "top",
        "pullover",
        "sweatshirt",
        "suit",
        "tie",
        "bow tie",
        "lady's suit",
        "waistcoat",
        "cardigan",
        "undershirt",
        "t-shirt",
        "bra",
        "scarf",
        "glove"
      ]
    },
    "bottom-accessories": {
      "description": "Cloth and accessories on the bottom part of the body",
      "misp-attribute": "text",
      "multiple": true,
      "ui-priority": 10,
      "values_list": [
        "trousers",
        "skirt",
        "underpants / panties",
        "shorts",
        "boxer shorts",
        "body stocking",
        "sock",
        "shoe",
        "boot",
        "sandal",
        "slipper",
        "sneaker",
        "hiking boot",
        "high tops"
      ]
    },
    "cloth-color": {
      "description": "Cloth's colors",
      "multiple": true,
      "misp-attribute": "text",
      "ui-priority": 1,
      "values_list": [
        "black",
        "white",
        "red",
        "green",
        "blue",
        "cyan",
        "orange",
        "violet",
        "pink",
        "yellow",
        "brown",
        "grey"
      ]
    },
    "cloth-picture": {
      "description": "Cloth's pictures",
      "misp-attribute": "attachment",
      "multiple": true,
      "ui-priority": 0
    }
  },
  "description": "Describes clothes a natural person wears",
  "meta-category": "misc",
  "name": "cloth",
  "required": [
    "description"
  ],
  "uuid": "d0f6c949-a47f-4be5-bc39-45033268bd89",
  "version": 1
}
