=== 0wlyW00d/misp-objects/schema_objects.json
{
  "$schema": "http://json-schema.org/schema#",
  "additionalProperties": false,
  "defs": {
    "attribute": {
      "additionalProperties": false,
      "properties": {
        "categories": {
          "items": {
            "type": "string"
          },
          "type": "array",
          "uniqueItems": true
        },
        "description": {
          "type": "string"
        },
        "disable_correlation": {
          "type": "boolean"
        },
        "misp-attribute": {
          "type": "string"
        },
        "multiple": {
          "type": "boolean"
        },
        "recommended": {
          "type": "boolean"
        },
        "sane_default": {
          "items": {
            "type": "string"
          },
          "type": "array",
          "uniqueItems": true
        },
        "to_ids": {
          "type": "boolean"
        },
        "ui-priority": {
          "type": "number"
        },
        "values_list": {
          "items": {
            "type": "string"
          },
          "type": "array",
          "uniqueItems": true
        }
      },
      "required": [
        "misp-attribute",
        "ui-priority",
        "description"
      ],
      "type": "object"
    }
  },
  "id": "https://www.github.com/MISP/misp-objects/schema.json",
  "properties": {
    "attributes": {
      "additionalProperties": {
        "$ref": "#/defs/attribute",
        "type": "object"
      },
      "type": "object"
    },
    "description": {
      "type": "string"
    },
    "meta-category": {
      "enum": [
        "file",
        "network",
        "financial",
        "misc",
        "internal",
        "vulnerability",
        "climate"
      ],
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "required": {
      "items": {
        "type": "string"
      },
      "type": "array",
      "uniqueItems": true
    },
    "requiredOneOf": {
      "items": {
        "type": "string"
      },
      "type": "array",
      "uniqueItems": true
    },
    "uuid": {
      "type": "string"
    },
    "version": {
      "type": "integer"
    }
  },
  "required": [
    "attributes",
    "version",
    "description",
    "meta-category",
    "name",
    "uuid"
  ],
  "title": "Validator for misp-objects",
  "type": "object"
}

=== 0wlyW00d/misp-objects/objects/narrative/definition.json
{
  "requiredOneOf": [
    "attachment",
    "archive",
    "narrative-summary"
  ],
  "attributes": {
    "5Ds-of-propaganda": {
      "description": "5 D's of propaganda are tactics of rebuttal used to defend against criticism and adversarial narratives.",
      "ui-priority": 1,
      "misp-attribute": "text",
      "disable_correlation": true,
      "multiple": true,
      "values_list": [
        "dismiss",
        "distort",
        "distract",
        "dismay",
        "divide"
      ]
    },
    "attachment": {
      "description": "Documents related to the narrative.",
      "ui-priority": 1,
      "misp-attribute": "attachment"
    },
    "narrative-disproof": {
      "description": "Disproof or evidence against the narrative.",
      "disable_correlation": true,
      "ui-priority": 1,
      "misp-attribute": "text"
    },
    "narrative-summary": {
      "description": "A summary of the narrative.",
      "ui-priority": 1,
      "misp-attribute": "text"
    },
    "external-references": {
      "description": "Link to external references.",
      "disable_correlation": true,
      "ui-priority": 1,
      "misp-attribute": "link"
    },
    "link": {
      "description": "Original link to the narrative source (Supposed harmless)",
      "ui-priority": 1,
      "misp-attribute": "link"
    },
    "url": {
      "description": "Original link to the narrative source (Supposed malicious)",
      "ui-priority": 1,
      "misp-attribute": "url"
    },
    "archive": {
      "description": "Archive of the original narrative source (Internet Archive, Archive.is, etc).",
      "disable_correlation": true,
      "ui-priority": 1,
      "multiple": true,
      "misp-attribute": "link"
    },
    "objective": {
      "description": "Objective of the narrative.",
      "ui-priority": 1,
      "misp-attribute": "text",
      "disable_correlation": true,
      "multiple": true,
      "sane_default": [
        "Disinformation",
        "Advertising",
        "Parody",
        "Other"
      ]
    }
  },
  "version": 4,
  "description": "Object describing a narrative.",
  "meta-category": "misc",
  "uuid": "83bea299-514a-4719-a84b-f6fd0997fac1",
  "name": "narrative"
}

=== 0wlyW00d/misp-objects/objects/regripper-software-hive-BHO/definition.json
{
    "required": [
      "key",
      "BHO-name"
    ],
    "attributes": {
      "key": {
        "description": "Software hive key where the information is retrieved from.",
        "ui-priority": 0,
        "misp-attribute": "text"
      },
      "last-write-time": {
        "description": "Date and time when the key was last updated.",
        "ui-priority": 0,
        "misp-attribute": "datetime"
      },
      "BHO-name": {
        "description": "Name of the browser helper object.",
        "ui-priority": 0,
        "misp-attribute": "text"
      },
      "BHO-key-last-write-time": {
        "description": "Date and time when the BHO key was last updated.",
        "ui-priority": 0,
        "misp-attribute": "datetime"
      },
      "class": {
        "description": "Class to which the BHO belongs to.",
        "ui-priority": 0,
        "misp-attribute": "text"
      },
      "module": {
        "description": "DLL module the BHO belongs to.",
        "ui-priority": 0,
        "misp-attribute": "text"
      },
      "comments": {
        "description": "Additional comments.",
        "ui-priority": 0,
        "misp-attribute": "text"
      },
      "references": {
        "description": "References to the BHO.",
        "ui-priority": 0,
        "misp-attribute": "links",
        "multiple":true
      }
    },
    "version": 1,
    "description": "Regripper Object template designed to gather information of the browser helper objects installed on the system.",
    "meta-category": "misc",
    "uuid": "e7b46b5a-d2d2-4a05-bc25-2ac8d4683ae2",
    "name": "regripper-software-hive-BHO"
  }

=== 0wlyW00d/misp-objects/objects/process/definition.json
{
  "name": "process",
  "uuid": "02aeef94-ac23-455c-addb-731757ceafb5",
  "meta-category": "misc",
  "description": "Object describing a system process.",
  "version": 6,
  "attributes": {
    "creation-time": {
      "description": "Local date/time at which the process was created.",
      "ui-priority": 0,
      "misp-attribute": "datetime",
      "disable_correlation": true
    },
    "start-time": {
      "description": "Local date/time at which the process was started.",
      "ui-priority": 0,
      "misp-attribute": "datetime",
      "disable_correlation": true
    },
    "name": {
      "description": "Name of the process",
      "ui-priority": 1,
      "misp-attribute": "text"
    },
    "pid": {
      "description": "Process ID of the process.",
      "ui-priority": 1,
      "misp-attribute": "text",
      "disable_correlation": true
    },
    "parent-pid": {
      "description": "Process ID of the parent process.",
      "ui-priority": 1,
      "misp-attribute": "text",
      "disable_correlation": true
    },
    "child-pid": {
      "description": "Process ID of the child(ren) process.",
      "ui-priority": 1,
      "misp-attribute": "text",
      "multiple": true,
      "disable_correlation": true
    },
    "process-state": {
      "description": "State of process.",
      "sane_default": [
        "D uninterruptible sleep (usually IO)",
        "R running or runnable (on run queue)",
        "S interruptible sleep (waiting for an event to complete)",
        "T stopped by job control signal",
        "t stopped by debugger during the tracing",
        "W paging (not valid since the 2.6.xx kernel)",
        "X dead (should never be seen)",
        "Z defunct ('zombie') process, terminated but not reaped by its parent",
        "< high-priority (not nice to other users)",
        "N low-priority (nice to other users)",
        "L has pages locked into memory (for real-time and custom IO)",
        "s is a session leader",
        "l is multi-threaded (using CLONE_THREAD, like NPTL pthreads do)",
        "+ is in the foreground process group"
      ],
      "ui-priority": 1,
      "misp-attribute": "text",
      "multiple": false,
      "disable_correlation": true
    },
    "fake-process-name": {
      "description": "Is the process spawned under a false name.",
      "sane_default": [
        "1",
        "0"
      ],
      "ui-priority": 1,
      "misp-attribute": "boolean",
      "multiple": false,
      "disable_correlation": true
    },
    "port": {
      "description": "Port(s) owned by the process.",
      "ui-priority": 1,
      "misp-attribute": "src-port",
      "multiple": true,
      "disable_correlation": true
    },
    "command-line": {
      "description": "Command line of the process",
      "ui-priority": 1,
      "misp-attribute": "text"
    },
    "current-directory": {
      "description": "Current working directory of the process",
      "ui-priority": 2,
      "misp-attribute": "text",
      "disable_correlation": true
    },
    "image": {
      "description": "Path of process image",
      "ui-priority": 1,
      "misp-attribute": "filename"
    },
    "parent-command-line": {
      "description": "Command line of the parent process",
      "ui-priority": 1,
      "misp-attribute": "text"
    },
    "parent-image": {
      "description": "Path of parent process image",
      "ui-priority": 1,
      "misp-attribute": "filename"
    },
    "user": {
      "description": "User context of the process",
      "ui-priority": 2,
      "misp-attribute": "text",
      "disable_correlation": true
    },
    "integrity-level": {
      "description": "Integrity level of the process",
      "ui-priority": 2,
      "misp-attribute": "text",
      "disable_correlation": true
    }
  },
  "requiredOneOf": [
    "name",
    "pid",
    "image",
    "command-line",
    "current-directory"
  ]
}

=== 0wlyW00d/misp-objects/objects/twitter-account/definition.json
{
  "attributes": {
    "archive": {
      "description": "Archive of the account (Internet Archive, Archive.is, etc).",
      "disable_correlation": true,
      "misp-attribute": "link",
      "multiple": true,
      "ui-priority": 1
    },
    "attachment": {
      "description": "A screen capture or exported list of contacts etc.",
      "misp-attribute": "attachment",
      "multiple": true,
      "ui-priority": 1
    },
    "description": {
      "description": "A description of the user.",
      "disable_correlation": true,
      "misp-attribute": "text",
      "ui-priority": 1
    },
    "displayed-name": {
      "description": "Displayed name.",
      "misp-attribute": "text",
      "ui-priority": 1
    },
    "embedded-link": {
      "description": "Link embedded in the user description (potentially malicious).",
      "misp-attribute": "url",
      "multiple": true,
      "ui-priority": 0
    },
    "embedded-safe-link": {
      "description": "Link embedded in the user description (supposed safe).",
      "misp-attribute": "link",
      "multiple": true,
      "ui-priority": 0
    },
    "followers": {
      "description": "number of followers.",
      "disable_correlation": true,
      "misp-attribute": "text",
      "ui-priority": 1
    },
    "friends": {
      "description": "Number of friends.",
      "disable_correlation": true,
      "misp-attribute": "text",
      "ui-priority": 1
    },
    "hashtag": {
      "description": "Hashtag embedded in the user description.",
      "misp-attribute": "text",
      "multiple": true,
      "ui-priority": 1
    },
    "id": {
      "description": "Numeric account id.",
      "misp-attribute": "text",
      "ui-priority": 1
    },
    "link": {
      "description": "Original link to the user (supposed harmless).",
      "misp-attribute": "link",
      "ui-priority": 1
    },
    "listed": {
      "description": "Number of lists the user is on.",
      "disable_correlation": true,
      "misp-attribute": "text",
      "ui-priority": 1
    },
    "location": {
      "description": "User description of location.",
      "disable_correlation": true,
      "misp-attribute": "text",
      "ui-priority": 1
    },
    "name": {
      "description": "User's screen name (without the @).",
      "misp-attribute": "text",
      "ui-priority": 1
    },
    "url": {
      "description": "Original URL location of the user (potentially malicious).",
      "misp-attribute": "url",
      "ui-priority": 1
    },
    "verified": {
      "description": "User verified.",
      "misp-attribute": "text",
      "sane_default": [
        "True",
        "False"
      ],
      "ui-priority": 1
    }
  },
  "description": "Twitter account.",
  "meta-category": "misc",
  "name": "twitter-account",
  "requiredOneOf": [
    "name",
    "id",
    "description",
    "archive",
    "link"
  ],
  "uuid": "8066563f-881e-4f6a-9d6c-a9d15b8658bb",
  "version": 1
}

=== 0wlyW00d/misp-objects/objects/anonymisation/definition.json
{
  "requiredOneOf": [
    "description",
    "method",
    "key",
    "keyed-hash-function",
    "encryption-function",
    "regexp",
    "iv"
  ],
  "attributes": {
    "method": {
      "description": "Anonymisation (pseudo or not) method(s) used",
      "ui-priority": 1,
      "disable_correlation": true,
      "sane_default": [
        "hiding - Attribute is replaced with a constant value (typically 0) of the same size. Sometimes called 'black marker'.",
        "hash - A hash function maps each attribute to a new (not necessarily unique) attribute.",
        "permutation - Maps each original value to a unique new value.",
        "prefix-preserving - Any two values that had the same n-bit prefix before anonymization will still have the same n-bit prefix as each other after anonymization. (Would be more accurately called 'prefix-relationship-preserving', because the actual prefix values are not preserved.) ",
        "shift - Adds a fixed offset to each value/attribute.",
        "enumeration - Map each original value to a new value such that their ordering is preserved.",
        "partitioning - Possible values are partitioned into meaningful sets; actual values are replaced with a fixed value from the same set. E.g., TCP port numbers 0 to 1023 are replaced with 0, and 1024 to 65535 replaced with 65535.",
        "updated - Checksums are recalculated to reflect changes made to other fields.",
        "truncation - Field is shortened, losing data at the end.",
        "encryption - Attribute is encrypted."
      ],
      "misp-attribute": "text",
      "multiple": true
    },
    "key": {
      "description": "Key (such as a PSK in a keyed-hash-function) used to anonymise the attribute",
      "ui-priority": 1,
      "disable_correlation": true,
      "misp-attribute": "text"
    },
    "iv": {
      "description": "Initialisation vector for the encryption function used to anonymise the attribute",
      "ui-priority": 1,
      "disable_correlation": true,
      "misp-attribute": "text"
    },
    "keyed-hash-function": {
      "description": "Keyed-hash function used to anonymise the attribute",
      "ui-priority": 1,
      "disable_correlation": true,
      "sane_default": [
        "hmac-sha1",
        "hmac-md5",
        "hmac-sha256",
        "hmac-sha384",
        "hmac-sha512"
      ],
      "misp-attribute": "text"
    },
    "encryption-function": {
      "description": "Encryption function or algorithm used to anonymise the attribute",
      "ui-priority": 1,
      "disable_correlation": true,
      "sane_default": [
        "bf-cbc",
        "bf",
        "blowfish",
        "bf-cfb",
        "bf-ecb",
        "bf-ofb",
        "cast-cbc",
        "cast",
        "cast5-cbc",
        "cast5-cfb",
        "cast5-ecb",
        "cast5-ofb",
        "des-cbc",
        "des",
        "des-cfb",
        "des-ofb",
        "des-ecb",
        "des-ede-cbc",
        "des-ede",
        "des-ede-cfb",
        "des-ede-ofb",
        "des-ede3-cbc",
        "des-ede3",
        "des3",
        "des-ede3-cfb",
        "des-ede3-ofb",
        "desx",
        "gost89",
        "gost89-cnt",
        "idea-cbc",
        "idea",
        "idea-cfb",
        "idea-ecb",
        "idea-ofb",
        "rc2-cbc",
        "rc2",
        "rc2-cfb",
        "rc2-ecb",
        "rc2-ofb",
        "rc2-64-cbc",
        "rc2-40-cbc",
        "rc4",
        "rc4-64",
        "rc4-40",
        "rc5-cbc",
        "rc5",
        "rc5-cfb",
        "rc5-ecb",
        "rc5-ofb",
        "seed-cbc",
        "seed",
        "seed-cfb",
        "seed-ecb",
        "seed-ofb",
        "sm4-cbc",
        "sm4",
        "sm4-cfb",
        "sm4-ctr",
        "sm4-ecb",
        "sm4-ofb",
        "aes-128-cbc",
        "aes128",
        "aes-128-cfb",
        "aes-128-cfb1",
        "aes-128-cfb8",
        "aes-128-ctr",
        "aes-128-ecb",
        "aes-128-ofb",
        "aes-128-cbc",
        "aes128",
        "aes-192-cfb",
        "aes-192-cfb1",
        "aes-192-cfb8",
        "aes-192-ctr",
        "aes-192-ecb",
        "aes-192-ofb",
        "aes-192-cbc",
        "aes192",
        "aes-256-cfb",
        "aes-256-cfb1",
        "aes-256-cfb8",
        "aes-256-ctr",
        "aes-256-ecb",
        "aes-256-ofb",
        "camellia-128-cbc",
        "camellia128",
        "camellia-128-cfb",
        "camellia-128-cfb1",
        "camellia-128-cfb8",
        "camellia-128-ctr",
        "camellia-128-ecb",
        "camellia-128-ofb",
        "camellia-192-cbc",
        "camellia192",
        "camellia-192-cfb",
        "camellia-192-cfb1",
        "camellia-192-cfb8",
        "camellia-192-ctr",
        "camellia-192-ecb",
        "camellia-192-ofb",
        "camellia-256-cbc",
        "camellia256",
        "camellia-256-cfb",
        "camellia-256-cfb1",
        "camellia-256-cfb8",
        "camellia-256-ctr",
        "camellia-256-ecb",
        "camellia-256-ofb"
      ],
      "misp-attribute": "text"
    },
    "regexp": {
      "description": "Regular expression to perfom the anonymisation (reversible or not)",
      "ui-priority": 10,
      "disable_correlation": true,
      "misp-attribute": "text"
    },
    "description": {
      "description": "Description of the anonymisation technique or tool used",
      "ui-priority": 1,
      "disable_correlation": true,
      "misp-attribute": "text"
    }
  },
  "version": 1,
  "description": "Anonymisation object describing an anonymisation technique which is used in MISP anonymised attributes. Reference: https://www.caida.org/tools/taxonomy/anonymization.xml",
  "meta-category": "misc",
  "uuid": "5867cffe-60ff-44f6-b097-e5f36b5de0ac",
  "name": "anonymisation"
}

=== 0wlyW00d/misp-objects/objects/shortened-link/definition.json
{
  "required": [
    "url",
    "shortened-url"
  ],
  "attributes": {
    "first-seen": {
      "description": "First time this shortened URL has been seen",
      "disable_correlation": true,
      "ui-priority": 0,
      "misp-attribute": "datetime"
    },
    "url": {
      "description": "Redirected to URL",
      "ui-priority": 1,
      "misp-attribute": "url"
    },
    "shortened-url": {
      "description": "Shortened URL",
      "ui-priority": 1,
      "misp-attribute": "url"
    },
    "domain": {
      "description": "Full domain",
      "ui-priority": 0,
      "misp-attribute": "domain"
    },
    "credential": {
      "description": "Credential (username, password)",
      "ui-priority": 0,
      "misp-attribute": "text"
    },
    "text": {
      "description": "Description and context of the shortened URL ",
      "ui-priority": 0,
      "misp-attribute": "text"
    }
  },
  "version": 1,
  "description": "Shortened link and its redirect target",
  "meta-category": "network",
  "uuid": "99c2857c-689f-11e8-adc0-fa7ae01bbebc",
  "name": "shortened-link"
}

=== 0wlyW00d/misp-objects/objects/regripper-system-hive-network-information/definition.json
{
    "required": [
      "network-key"
    ],
    "attributes": {
      "network-key": {
        "description": "Registry key assigned to the network",
        "ui-priority": 0,
        "misp-attribute": "text"
      },
      "network-key-last-write-time": {
        "description": "Date and time when the network key was last updated.",
        "ui-priority": 0,
        "misp-attribute": "datetime"
      },
      "network-key-path": {
        "description": "Path of the key where the information is retrieved from.",
        "ui-priority": 0,
        "misp-attribute": "text"
      },
      "TCPIP-key": {
        "description": "TCPIP key",
        "ui-priority": 0,
        "misp-attribute": "text"
      },
      "TCPIP-key-last-write-time": {
        "description": "Datetime when the key was last updated.",
        "ui-priority": 0,
        "misp-attribute": "datetime"
      },
      "DHCP-domain": {
        "description": "Name of the DHCP domain service",
        "ui-priority": 0,
        "misp-attribute": "text"
      },
      "DHCP-IP-address": {
        "description": "DHCP service - IP address",
        "ui-priority": 0,
        "misp-attribute": "ip-dist"
      },
      "DHCP-subnet-mask": {
        "description": "DHCP subnet mask - IP address.",
        "ui-priority": 0,
        "misp-attribute": "ip-dist"
      },
      "DHCP-name-server": {
        "description": "DHCP Name server - IP address.",
        "ui-priority": 0,
        "misp-attribute": "ip-dist"
      },
      "DHCP-server": {
        "description": "DHCP server - IP address.",
        "ui-priority": 0,
        "misp-attribute": "ip-dist"
      },
      "interface-GUID": {
        "description": "GUID value assigned to the interface.",
        "ui-priority": 0,
        "misp-attribute": "text"
      },
      "interface-last-write-time": {
        "description": "Last date and time when the interface key was updated.",
        "ui-priority": 0,
        "misp-attribute": "datetime"
      },
      "interface-name": {
        "description": "Name of the interface.",
        "ui-priority": 0,
        "misp-attribute": "text"
      },
      "interface-PnpInstanceID": {
        "description": "Plug and Play instance ID assigned to the interface.",
        "ui-priority": 0,
        "misp-attribute": "text"
      },
      "interface-MediaSubType": {
        "description": "",
        "ui-priority": 0,
        "misp-attribute": "number"
      },
      "interface-IPcheckingEnabled": {
        "description": "",
        "ui-priority": 0,
        "misp-attribute": "boolean"
      }
    },
    "version": 1,
    "description": "Regripper object template designed to gather network information from the system-hive.",
    "meta-category": "misc",
    "uuid": "a5a3ba3a-ba2e-42a4-be45-b36809ae56f0",
    "name": "regripper-system-hive-network-information."
  }

=== 0wlyW00d/misp-objects/objects/translation/definition.json
{
  "attributes": {
    "original-text": {
      "description": "Original text",
      "ui-priority": 1,
      "misp-attribute": "text"
    },
    "translated-text": {
      "description": "Text after translation",
      "ui-priority": 1,
      "misp-attribute": "text"
    },
    "original-language": {
      "description": "Language of the original text",
      "ui-priority": 1,
      "misp-attribute": "text"
    },
    "translation-language": {
      "description": "Language of translation",
      "ui-priority": 1,
      "misp-attribute": "text"
    },
    "translation-service": {
      "description": "translation service used for the translation",
      "ui-priority": 1,
      "misp-attribute": "text"
    }
  },
  "version": 1,
  "description": "Used to keep a text and its translation",
  "meta-category": "misc",
  "uuid": "a43b54fa-dac9-11e9-9b0d-97296aceae1a",
  "name": "translation"
}
